name: Develop Deploy

on:
  push:
    branches:
      - 'develop'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSHKEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/projects/dev-api.foodtracker.pl/server/

      - name: Execute SSH commmands on remote server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /home/projects/dev-api.foodtracker.pl/server
            docker stop dev-foodtracker-server
            docker rm dev-foodtracker-server
            docker-compose -f docker-compose-dev.yaml up -d --build
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSHKEY}}


